name: ahflnew
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  flutter_staggered_grid_view: ^0.6.1
  flutter_animate: ^4.1.1+1
  shimmer: ^3.0.0
  animate_do: ^4.2.0

  http: ^1.1.0 #^0.13.4
  #shared_preferences: ^2.0.0
  file_picker: ^6.1.1
  syncfusion_flutter_pdfviewer: ^28.2.7 #^24.1.41
  image_picker: ^1.0.7

  cupertino_icons: ^1.0.8
  mongo_dart: ^0.10.4
  carousel_slider: ^5.0.0
  excel: ^2.1.0  # For creating Excel files
  file_saver: ^0.2.12 
  shared_preferences: ^2.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/
  #   - images/a_dot_ham.jpeg
